site:
  title: BAMM Aspect Meta Model
  url: https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/
  start_page: bamm-specification::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: src/docs
      tags: '*'
ui:
  bundle:
    url: ./src/docs/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
runtime:
  cache_dir: ./.cache/antora
asciidoc:
  attributes:
    doctype: book
    sectanchors: true
    idprefix: ''
    idseparator: '-'
    stem: 'asciimath'
    ok: 'icon:check-circle[role="green",size="2x"]'
    nok: 'icon:times-circle[role="red",size="2x"]'
    meta-model-version: 1.0.0@
    meta-model-full-name: BAMM Aspect Meta Model
    meta-model-abbr: BAMM
    omp: Open Manufacturing Platform
    omp-abbr: OMP
    bamm: urn:bamm:org.open-manufacturing.digitaltwin:meta-model:1.0.0#@
    bamm-c: urn:bamm:org.open-manufacturing.digitaltwin:characteristic:1.0.0#@
    bamm-e: urn:bamm:org.open-manufacturing.digitaltwin:entity:1.0.0#@
    unit:  urn:bamm:org.open-manufacturing.digitaltwin:unit:1.0.0#@
    example-ns: com.mycompany@

