name: Check Pull Request
on:
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}

    - name: Cache node and node_modules
      uses: actions/cache@v3
      with:
        path: |
          documentation/node
          documentation/node_modules
        key: node-${{ hashFiles('documentation/package-lock.json') }}

    - name: Build
      run: |
        ./mvnw generate-resources -pl documentation -Pantora
        ./mvnw clean install -pl esmf-samm-build-plugin
        ./mvnw clean package -pl esmf-semantic-aspect-meta-model
