name: Release Artifact
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true
jobs:
  build-and-release:
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      PGP_KEY: ${{ secrets.PGP_KEY }}
      PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}

    - name: Cache node and node_modules
      uses: actions/cache@v3
      with:
        path: |
          documentation/node
          documentation/node_modules
        key: node-${{ hashFiles('documentation/package-lock.json') }}

    - name: Build SAMM artifact and release to OSSRH
      run: |
        ./mvnw versions:set -DnewVersion=${{ github.event.inputs.release_version }}
        ./mvnw versions:commit
        ./mvnw generate-resources -pl documentation -Pantora
        ./mvnw clean install -pl esmf-samm-build-plugin
        ./mvnw clean deploy -pl esmf-semantic-aspect-meta-model -Psign

    - name: Upload SAMM JAR
      uses: actions/upload-artifact@v2
      with:
        name: samm-artifacts
        path: esmf-semantic-aspect-meta-model/target/*.jar
