name: Release Artifact
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true
jobs:
  build-and-maven-release:
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      PGP_KEY: ${{ secrets.PGP_KEY }}
      PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}
      REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build SAMM artifact and release to OSSRH
      run: |
        ./mvnw clean install -pl esmf-samm-build-plugin
        ./mvnw clean deploy -pl esmf-semantic-aspect-meta-model
    - name: Upload SAMM JAR
      uses: actions/upload-artifact@v2
      with:
        name: samm-artifacts
        path: esmf-semantic-aspect-meta-model/target/
